name: Profile Readme Dev Stats
on:
  workflow_dispatch:
  schedule:
    # Runs every monday at 12AM UTC
    - cron: "15 16 * * 6"
  # You may pin to the exact commit or the version.

jobs:
  update-readme:
    name: Update this repo's README
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          # Github access token with Repo Scope
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          # Wakatime API key
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          SHOW_TOTAL_CODE_TIME: "False"
          SHOW_LOC_CHART: "False"
          # Github Summary
          SHOW_SHORT_INFO: "False"
          # Shows timezone. Requires SHOW_BREAK_DOWN=true
          SHOW_TIMEZONE: "True"
          # Shows editors used in the week SHOW_BREAK_DOWN=true
          SHOW_EDITORS: "True"
          # Show week coding language breakdown
          SHOW_LANGUAGE: "True"
          # Shows Operating System
          SHOW_OS: "False"
          # Shows github repo language counts
          SHOW_LANGUAGE_PER_REPO: "True"
          # Show Projects worked on that week
          SHOW_PROJECTS: "False"
         
            
